- name: Install Nginx on Web Server
  hosts: localhost
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      package:
        name: nginx
        state: present