- name: Install Nginx
  hosts: localhost
  become_method: su
  become_exe: sudo su -
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Nginx
      package:
        name: nginx
        state: present
      become: yes

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      become: yes